"""
Module to launch the wombat GUI 

This script is called directly via the command line and uses a set of passed
parameters to launch WOMBAT in one of two modes:
    PickleMode - passing a pickle generated by wombatProcessObs.py
    ReloadMode -  passing a logFile and list off log lines

There are optional parameters which differ slightly depending on which mode is used

PickleMode:
    python3 wombatWrapper.py wbPickles/pickle.pkl [nwfs, ovw, tRes, noFigLabs]

ReloadMode
    python3 wombatWrapper.py wbOutputs/logFile.txt line(s) [ovw, tRes, noFigLabs]

The call needs to be to python 3, this may be python3 or just python depending on 
your system setup.

WOMBAT defaults to saving pickles in wbPickles/ and log files in wbOutputs. They don't
have to live in these folders, just point the first argument after wombatWrapper.py to
wherever they actually are.

For pickleMode the number of wireframes (nwfs) can be specified by passing an integer
after the pkl file. If not provided it defaults to 1. 

For reloadMode the specific lines within the logFile must be provided as the second
argument. It can be a single integer (e.g. 4), a range of lines (e.g. 4-10), or a list 
of single lines connected by + (e.g. 4+8+12). You cannot specify the number of wireframes
in the command line. The selected log lines must use the same WOMBAT pickle but can include
multiple wireframes and multiple instruments. You cannot select multiple fits for the 
same wireframe at the same time.

The remaining arguments are optional, can be provided in any order and work for both modes
    ovw - flag to include the overview window 

    tRes - time resolution (in minutes) for the global time slider. given as tres# where
           # is an integer (e.g. tres10 would set 10 min resolution)
           defaults to 20 minute resolution

    noFigLabs - flag to turn off figure labels (instrument name + time) when saving figures

Outputs:
    No outputs automatically generated. If the save button is hit then figures will be saved
    within wbOutputs/ as wombat_SAT+INST_YYYY-MM-DD-THHMMSS.png 

    If the log button is hit lines will be appended to the log file. The
    default log file (if none was provided) is wbOutputs/WomBlog.txt and each line contains:
        1.    time of fit  
        2.    instrument
        3.    time of observation
        4.    WF type + panel number (e.g. GCS1). Adding panel number allows multiple of same type
        5-13. WF parameter values. If a type has <9 parameters the extras are filled with None
        14.   the WOMBAT pickle
        15.   the index of the obs time in this pickle
        16.   the background difference mode (0 running diff, 1 base diff)
        17.   the scaling mode (1 linear, 2 log, 3 sqrt)
        18.   the min brightness setting (0-256)
        19.   the max brightness setting (0-256)
        
    The amount of figures saved/lines logged depends on whether one clicks a save/log button or the 
    active window when one hits the s/l short cut keys

External Calls:
    releaseTheWombat from wombatGUI
    setupTimeStuff from wombatProcessObs


"""

from astropy.io import fits
import astropy.units as u
import numpy as np
import sunpy.map
from sunpy.time import parse_time
import sys, os
import pickle
import sunpy

# |--------------------------------|
# |------- Euro Mode Testing ------|
# |--------------------------------|
# Can turn this on to test using 
# commas in text box numbers 
#from PyQt5.QtCore import QLocale
#locale = QLocale(QLocale.German, QLocale.Germany)
#QLocale.setDefault(locale)


# |------------------------------------|
# |------- Import Wombat Friends ------|
# |------------------------------------|
sys.path.append('wombatCode/') 
from wombatGUI import releaseTheWombat
from wombatProcessObs import setupTimeStuff

# |--------------------------------|
# |------- Suppress Warnings ------|
# |--------------------------------|
# Astropy/sunpy have a lot of thoughts about missing
# keywords so set the logger to only complain about
# actual errors not all warnings
import logging
logging.basicConfig(level='INFO')
slogger = logging.getLogger('sunpy')
slogger.setLevel(logging.ERROR)
alogger = logging.getLogger('astropy')
alogger.setLevel(logging.ERROR)


# |------------------------------------------------------------|
# |------------------- Process log reload ---------------------|
# |------------------------------------------------------------|
def reloadLogLine(theFile, lineIds):
    """
    Function to process a log line reload 
    
    This will take a wombat log (womblog) and line number(s) and set up
    a reload file analogous to the processReload version

    Inputs:
        fileIn: a text file with two columns (keyword value)
    
        lineIds: a string representing the line(s) to reload. It can be:
                    - single integer (e.g. 4)
                    - range of lines (e.g. 4-10)
                    - list of single lines connected by + (e.g. 4+8+12). 
                The selected log lines can have diff wf types and instruments 
                but must use the same pickle. You cannot have multiple lines 
                for the same time and wftype but different WF parameters
      
    Outputs:
        bkgData: the background data pickle. theFile is opened and the pickle
                 is passed back to the wrapper
    
        reloadDict: a dictionary with the saved parameters from the reload file. It
                    will be used to set up the gui to the previous configuration
    
        nWFs: the number of wireframes
        
            
    """
    #|--------------------------|
    #|--- Check the log file ---|     
    #|--------------------------|
    # Check it exists and is a text file
    if not os.path.exists(theFile):
        print ('Cannot find log file. Check location and/or call syntax')
    else:
        try:
            logFile = np.genfromtxt(theFile, dtype=str)
        except:
            sys.exit('Error opening logFile, check that it is a WOMBAT log file')
            
    #|-------------------------|
    #|--- Check the log ids ---|     
    #|-------------------------|
    # Process the string to make sure it is one of the 
    # three allowed formats
    idstr = lineIds
    nplus = idstr.count('+')
    singleWF = True # will overwrite later
    
    # Range in ids
    if '-' in idstr:
        if '+' in idstr:
            sys.exit('Cannot process ids with both + and -')
        splitstr = idstr.split('-')
        if len(splitstr) > 2:
            sys.exit('Cannot process ids with multiple -')
        ids = np.arange(int(splitstr[0]), int(splitstr[1])+1,1, dtype=int)
    # Series of specific ids     
    elif '+' in idstr:
        splitstr = idstr.split('+')
        ids = []
        for aStr in splitstr:
            try:
                ids.append(int(aStr))
            except:
                print ('Error in converting id string to individual ids. Error at', aStr)
                           
    else:
        try:
            ids = [int(idstr)]
        except:
            print ('Error in converting id string to individual ids. Error from', idstr)
            sys.exit()
    
    ids = np.array(ids)            
    miniLog = logFile[ids-1,:] # indexing starts at 0 not 1
    
     
    #|------------------------------|
    #|--- Process basic log data ---|     
    #|------------------------------|
    reloadDict = {}
    
    # |--- Check background pickle ---|
    # Must be same for all, can't swap in GUI (at least right now)
    uniqPickles = np.unique(miniLog[:, 13])
    if len(uniqPickles) != 1:
        sys.exit('Different background pickles passed, cannot reload')
    thePickle =  miniLog[0,13]  
    reloadDict['BkgPickle'] = thePickle
    with open(thePickle, 'rb') as file:
        bkgData = pickle.load(file)
    bkgData['pickleSource'] = thePickle
        
    # |--- Get number of WFs ---|
    wfTypes = np.unique(miniLog[:,3])
    nWFs = len(wfTypes)
    if nWFs > 5:
        sys.exit('Max limit of 5 wireframes')
    for i in range(nWFs):
        wfTypes[i] = wfTypes[i].replace('Half', 'Half ')
    reloadDict['nWFs'] = nWFs
    reloadDict['wfTypes'] = wfTypes
    
    #|-----------------------------|
    #|--- Populate reload by WF ---|     
    #|-----------------------------|
    reloadDict['Params'] = {}
    reloadDict['PTimes'] = {}
    reloadDict['Pidx']  = {}
    reloadDict['PlotVals'] = {}
    uniqInst = np.unique(miniLog[:, 1])
    for aInst in uniqInst:
        reloadDict['Pidx'][aInst]  = {}
        reloadDict['PlotVals'][aInst]  = {}
        
    for aWF in wfTypes:
        reloadDict['Params'][aWF] = {}
        thisWF = np.where(miniLog[:,3] == aWF)[0]
        for idx in thisWF:
            myInst = miniLog[idx, 1]
            myTime = miniLog[idx,2][:-3]
            myParams = miniLog[idx,4:13]
            myParams = myParams[myParams != 'None'].astype(float)
            
            if myTime in reloadDict['Params'][aWF].keys():
                for j in range(len(myParams)):
                    if reloadDict['Params'][aWF][myTime][j] != myParams[j]:
                        print ('Multiple params for '+aWF+ ' at '+myTime)
                        print (myParams)
                        print (reloadDict['Params'][aWF][myTime])
                        sys.exit('Disagreement in parameters for '+aWF+ ' at '+myTime)
            else:
                reloadDict['Params'][aWF][myTime] = myParams
            
            if myTime in reloadDict['Pidx'][myInst].keys():
                if reloadDict['Pidx'][myInst][myTime] != miniLog[idx, 14]:
                    sys.exit('Mismatch in pickle index for '+myInst+' at '+myTime)
            else:
                reloadDict['Pidx'][myInst][myTime] = miniLog[idx, 14]
            
            reloadDict['PlotVals'][myInst][myTime] = miniLog[idx, 15:] 

    return bkgData, reloadDict, nWFs

# |------------------------------------------------------------|
# |----------------------- Main Wrapper -----------------------|
# |------------------------------------------------------------|
def runWombat(args):
    ''' 
    This script is called directly via the command line and uses a set of passed
    parameters to launch WOMBAT in one of two modes:
        PickleMode - passing a pickle generated by wombatProcessObs.py
        ReloadMode -  passing a logFile and list off log lines

    There are optional parameters which differ slightly depending on which mode is used

    PickleMode:
        python3 wombatWrapper.py wbPickles/pickle.pkl [nwfs, ovw, tRes, noFigLabs]

    ReloadMode
        python3 wombatWrapper.py wbOutputs/logFile.txt line(s) [ovw, tRes, noFigLabs]

    The call needs to be to python 3, this may be python3 or just python depending on 
    your system setup.

    WOMBAT defaults to saving pickles in wbPickles/ and log files in wbOutputs. They don't
    have to live in these folders, just point the first argument after wombatWrapper.py to
    wherever they actually are.

    For pickleMode the number of wireframes (nwfs) can be specified by passing an integer
    after the pkl file. If not provided it defaults to 1. 

    For reloadMode the specific lines within the logFile must be provided as the second
    argument. It can be a single integer (e.g. 4), a range of lines (e.g. 4-10), or a list 
    of single lines connected by + (e.g. 4+8+12). You cannot specify the number of wireframes
    in the command line. The selected log lines must use the same WOMBAT pickle but can include
    multiple wireframes and multiple instruments. You cannot select multiple fits for the 
    same wireframe at the same time.

    The remaining arguments are optional, can be provided in any order and work for both modes
        ovw - flag to include the overview window 

        tRes - time resolution (in minutes) for the global time slider. given as tres# where
               # is an integer (e.g. tres10 would set 10 min resolution)
               defaults to 20 minute resolution

        noFigLabs - flag to turn off figure labels (instrument name + time) when saving figures

    Outputs:
        No outputs automatically generated. If the save button is hit then figures will be saved
        within wbOutputs/ as wombat_SAT+INST_YYYY-MM-DD-THHMMSS.png 

        If the log button is hit lines will be appended to the log file. The
        default log file (if none was provided) is wbOutputs/WomBlog.txt and each line contains:
            1.    time of fit  
            2.    instrument
            3.    time of observation
            4.    WF type + panel number (e.g. GCS1). Adding panel number allows multiple of same type
            5-13. WF parameter values. If a type has <9 parameters the extras are filled with None
            14.   the WOMBAT pickle
            15.   the index of the obs time in this pickle
            16.   the background difference mode (0 running diff, 1 base diff)
            17.   the scaling mode (1 linear, 2 log, 3 sqrt)
            18.   the min brightness setting (0-256)
            19.   the max brightness setting (0-256)
        
        The amount of figures saved/lines logged depends on whether one clicks a save/log button or the 
        active window when one hits the s/l short cut keys

    External Calls:
        releaseTheWombat from wombatGUI
        setupTimeStuff from wombatProcessObs

    
    '''
    
    theFile = args[1]
    doReload     = False
    overviewPlot = False
    logFile      = None
    doFigLabs = True
    tRes = 10
    
    #|-------------------------------|
    #|--- Check for output folder ---|     
    #|-------------------------------|
    if not os.path.exists('wbOutputs/'):
        os.mkdir('wbOutputs/')
        print ('Created output folder wbOutputs')
        
    #|---------------------------|
    #|--- Check the arguments ---|     
    #|---------------------------|
    
    # Check if the File is pkl or log file
    if ('.pkl' in theFile):
        reloadDict = None
        # Open the pickle
        with open(theFile, 'rb') as file:
            bkgData = pickle.load(file)
        bkgData['pickleSource'] = theFile
        nWFs = 1
        if len(args) >2:
            try: 
                nWFs = int(args[2])
                if nWFs > 5:
                    sys.exit('Max limit of 5 wireframes')
            except:
                print ('Setting number of wireframes to 1. Change by passing integer after pkl file')
        
    # Not pickle, assume logFile
    else:
        bkgData, reloadDict, nWFs = reloadLogLine(theFile, args[2])
        logFile = theFile.replace('.txt','').replace('wbOutputs/','')
        if logFile == 'WomBlog':
            logFile = None # just the name to save to... WomBlog is default
        
    # Check remaining for ovw, tRes, noFigLabs
    for arg in args[1:]:
        if arg.lower() in ['ovw', 'overviewplot', 'ovp']:
            overviewPlot = True
        elif arg.lower in ['nofiglabs', 'nolabs', 'nfl']:
            doFigLabs = False
        elif 'tres' in arg.lower():
            num = arg.lower().replace('tres','')
            try:
                tRes = int(num)
            except:
                sys.exit('Error in converting tRes into integer number of minutes')    
            
    releaseTheWombat(bkgData, reloadDict=reloadDict, overviewPlot=overviewPlot, nWFs=nWFs, logFile=logFile, tRes=tRes, doFigLabs=doFigLabs)   
        
        
if __name__ == '__main__':
    runWombat(sys.argv)
